### ISSUE TITLE
Load variables from all.yaml

### ISSUE THREAD

**Issue by jodybro** [thegeeklab/ansible-doctor#11]
Say I have a role that loads some values from `all.yaml`...how would I be able to export those values to markdown here?
The `{{ group_vars }}` ansible variable isnt available to this tool by default (which makes sense since its not targeting any group).

Would I be able to make a role called `all` or something and load the variables there?

**Comment by xoxys** [comment]
Not sure if I understand the question correctly. `ansible-doctor` will read all all `yaml|yml` files within the given role base dir. Let's say your roles dir looks like this:

```Shell
demo-role/
├── all.yaml
├── defaults
│   └── main.yml
├── HEADER.md
├── meta
│   └── main.yml
├── README.md
└── tasks
    └── main.yml
```

`all.yaml` annotations will be parsed as every other file and can be used in a template:

```
---
# @var test_from_all_dot_yaml:description: Annotation loaded from all.yaml of the current role
test_from_all_dot_yaml: example_value
```

**Comment by xoxys** [comment]
If you try to use annotations from a file outside the role's base dir, that's not supported and currently out of scope, sorry.

**Comment by jodybro** [comment]
Yeah that behaviour is perfectly fine but say I have a role that loads some values from `group_vars/all.yaml`. Then those arent loaded inside the `role` variable that this tool exposes.

The only variables that itll catch are role specific ones.

So what I was wondering if its possible to make a `all` role that would be able to load `group_vars` ?

**Comment by jodybro** [comment]
Ohhh
Ok thats understandable. This can be closed then.

Thanks!

**Comment by xoxys** [comment]
That's not how it is intended to use this tool :) we try to provide a proper way to document the role itself, the available variables and the default values. Therefor loading external files from e.g. group vars or host vars is not possible.
