### ISSUE TITLE
CLI feature to extend autodocumentation for playbooks

### ISSUE THREAD

**Issue by ptomas-adacis** [thegeeklab/ansible-doctor#132]
I am opening this issue with the idea to fork and making a pull request on this repository to add a CLI feature. Ansible-doctor is really helpful to add a documentation for my roles and I know that ansible-doctor is dedicated to and designed for Ansible roles. But I would like to use it also on my playbooks or on a(/several) file(s) without creating a "tasks" directory, a "default" directory and putting each annotated file inside. It would be very useful if ansible-doctor with a `-f` or `--files` flag with any number of arguments after, could:
1) parse annotations in the files given in the command line (and not in "default" and "meta" directories),
2) disable the role detection by checking if "tasks" directory is in the role directory.

Do you think that I could implement and add this feature ? If yes, do you have any suggestion or advice to allow me to start in the right way ?

**Comment by xoxys** [comment]
Thank you for your report. In general it would be possible and I would agree with such a change. Do you really need to pass files from the CLI. Wouldn't it be sufficient to bypass the role detection mechanism by a simple CLI flag? The files to be parsed would still have to be in the same base directory, of course.

**Comment by ptomas-adacis** [comment]
Thank you for your answer. I think you are right. The feature I suggested is too specific and only fits my need. It would be less time consuming and possibly more useful for other users to implement your idea. Do I have your consent to implement your idea on my ansible-doctor fork and make a pull request later ?

**Comment by xoxys** [comment]
Sure, happy to review a PR.

**Comment by xoxys** [comment]
Closed by https://github.com/thegeeklab/ansible-doctor/pull/135
