### ISSUE TITLE
ansible-doctor parses files not mentioned into documentation

### ISSUE THREAD

**Issue by ptomas-adacis** [thegeeklab/ansible-doctor#137]
For this file system:
```
.
├── default
│   └── main.yml
└── subset
    └── main.yml
```

default/main.yml:
```
# @var default_variable:value: >
# 2
# @end
```

subset/main.yml:
```
# @var subset_variable:value: >
# 1
# @end
```

I ran this command: `ansible-doctor -n` (same issue if I run `mkdir tasks && ansible-doctor`) and the generated `README.md` looks like (triple backticks replaced by triple single quotes):
```
# 

## Table of content

* [Default Variables](#default-variables)
  * [default_variable](#default_variable)
  * [subset_variable](#subset_variable)
* [Dependencies](#dependencies)
* [License](#license)
* [Author](#author)

---

## Default Variables

### default_variable

#### Default value

'''YAML
2
'''

### subset_variable

#### Default value

'''YAML
1
'''

## Dependencies

None.
```

The documentation mentions this:
```
After the successful check, ansible-doctor will try to read some static files into a dictionary:
* defaults/main.yml
* meta/main.yml
```

But with the above file system, ansible-doctor is clearly searching annotations into `subset/` directory to generate the `README.md`. Did I miss something ? Is it an expected behavior or is it the last update which lead to this issue ?

**Comment by xoxys** [comment]
That's correct, and the same behavior without `-n` flag. It just checks if the folder structure indicates that it is an Ansible role and add some extra logic to some files. But apart from that, the annotation parsing does not care about file or folder names as long as it is a valid yaml file.

**Comment by xoxys** [comment]
For me, that's expected behavior, especially as there is an `exclude_files` option but the docs can still be improved of course.

**Comment by ptomas-adacis** [comment]
Alright, thanks for your answer.
