### ISSUE TITLE
Add the ability to have line breaks in comments

### ISSUE THREAD

**Issue by FlxPeters** [thegeeklab/ansible-doctor#20]
I couldn't find a way to add line breaks to multi line comments. 

``` yaml
# @var demo_role_other_tags:description: >
# If a variable need some more explanation, \n
# this is a good place to do so.
# Maybe this way <br>
# @end
```
Is it possible or is any newline character removed by default?

**Comment by xoxys** [comment]
Thanks for your report. Right now that's not possible. The whitespace handling in general is a bit difficult. As we try to be smart multiline strings are parsed into a Json list, so they can be used in multiple output templates. During the raw comment data parsing we remove duplicate whitespace automatically and convert empty lines into a paragraph.

Raw data:

```
# @var demo_role_other_tags:description: >
# If a variable need some more explanation,
# this is a good place to do so.
#
# Maybe this way.
# @end
```

Parsed Json:

```
['If a variable need some more explanation,', 'this is a good place to do so.', '\n\nMaybe this way.']
```

This way, paragraphs are in general possible, but for the built-in templates we decided to use the `striptags` filter, see https://github.com/thegeeklab/ansible-doctor/blob/master/ansibledoctor/templates/readme/_vars.j2#L10

As a result, every newline/line break character is replaces by a single space. One way to solve it, is to write your own template. Another way is to improve the whitespace handling in general but I want to keep the built-in templates as simple as possible.

But I'm open to discuss possible solutions :)
