### ISSUE TITLE
No tags template

### ISSUE THREAD

**Issue by apollocreed** [thegeeklab/ansible-doctor#22]
There is no template for tags in the template dir. 
Because of that, tags wont be added to the generated markdown file. 
Same for Todos.
Moreover, teh README.j2 template does not include a tags nor todos sections.

**Comment by xoxys** [comment]
Thanks for your report. That's correct, as the whole project was reworked after the fork these annotations are not implemented right now.

**Comment by xoxys** [comment]
Tag handling is now included. Todo is still open.
