### ISSUE TITLE
Can't override variable value if it's already defined

### ISSUE THREAD

**Issue by DrySimon** [thegeeklab/ansible-doctor#280]
Hi,

I started using ansible-doctor to document my roles, and, following the documentation, I see that I should be able to override an existing variable value, like so: 

```YAML
---
# defaults file for test

# @var testvar:value: "foo"
testvar: "secret"
```

However, when I run `ansible-doctor`, I have an error: 

```
[CRITICAL] Unable to merge annotation values:
... too many values to unpack (expected 2) other=['"foo"']
```

Is this a normal behavior? 

Thanks a lot for your answer!

**Comment by xoxys** [comment]
Hi, Thanks for your report. That's because the documentation is wrong here. The value will always be parsed as json/yaml, but therefor you need to flag it with a `$`.

Example:

```
## Content after the $ need to be a valid json; this json will be translated to YAML for the generated docs.
## Simple value
# @var demo_role_override: $ "test"
demo_role_override: original

## Complex value
# @var demo_role_override_complex:value: $ {"foo":"bar", "second":"value"}
demo_role_override_complex: {}
``` 

Rendered docs output:

```YAML
demo_role_override: test
```

```YAML
demo_role_override_complex:
  foo: bar
  second: value
```

Quoting matters in this case as well. I'll fix the documentation later.

**Comment by xoxys** [comment]
Hope that helps. If not please let us know.

**Comment by DrySimon** [comment]
Hi, sorry for the delay! 

Thanks for the insight, it works like a charm!

**Comment by xoxys** [comment]
No worries, thanks for your feedback :)
