### ISSUE TITLE
Tag skiping

### ISSUE THREAD

**Issue by anshibanov** [thegeeklab/ansible-doctor#286]
Is there any way to skip some playbook tags? For example, I don't want the tags "never" and "always" to get into the documentation. everyone knows their meaning

**Comment by xoxys** [comment]
That's not possible yet. You don't need to add a description at all, but the intention was at least to list all available tags, so the user knows them and don't need to browse to all tasks files to figure it out.

However, we might be able to add an option to exclude tasks from auto-discovering.

**Comment by marcpaulchand** [comment]
I'm sorry to comment this issue, but it appear to be not helping.

I'm trying this following `ansibledoctor.yml` configuration:
```yaml
---
logging:
  level: warning
force_overwrite: true
exclude_tags:
  - always
  - never
```

And `never` tag still appear in autodiscovery tags section.

And i think I'm not the only one.
I even found this roles README with a `ansibledoctor.yml` configuration with `exclude_tags` where the mentionned tag appear in README (always)
https://github.com/oravirt/ansible-oracle/tree/master/roles/oraswgi_install

I also tried with an environment variable without succes : 
```sh
EXCLUDE_TAGS=["never"] ansible-doctor
```

**Comment by xoxys** [comment]
@marcpaulchand thanks for you feedack. Can you please create a new issue?
