### ISSUE TITLE
Default readme template lists dependencies as literal ordereddict objects

### ISSUE THREAD

**Issue by goldeelox** [thegeeklab/ansible-doctor#298]
Hello,
The default readme template lists dependencies as literal ordereddict objects.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-role-dependencies

## Steps to reproduce
1. Add the following dependency to example/demo-role/meta/main.yml
```yaml
dependencies:
  - role: example-role
```
3. Generate docs with no options

## Expected Result
```
## Dependencies

- example-role
```

## Actual Result
```
## Dependencies

- ordereddict([('role', 'example-role')])
```

**Comment by xoxys** [comment]
Good catch, thanks!
