### ISSUE TITLE
Playbooks autodocs

### ISSUE THREAD

**Issue by neo-escieur** [thegeeklab/ansible-doctor#335]
The use case :
one folder with multi playbooks and roles/requirements.
```
.
├── roles
│   └── requirements.yml
└── playbook_1.yml
└── playbook_2.yml
```

The expected result :

one document README.md or one document per playbook README_playbookname.md and the requirements listed in section "Dependencies" 

If this use case is outside the scope of this project, then I will probably fork it .

**Comment by xoxys** [comment]
Thats a bit out of scope, sorry.

**Comment by neo-escieur** [comment]
Ok, what do you prefer: I create a new branch on the fork or I create a new project using the current code.
