### ISSUE TITLE
Email link for the author such as in the example doesn't work

### ISSUE THREAD

**Issue by dan-wittenberg** [thegeeklab/ansible-doctor#367]
If you put the markdown around the author name/email it doesn't render anything into the README.md

**Comment by xoxys** [comment]
Thanks for reporting! That's because the annotation value contains a `:` which is also used as delimiter in the annotation itself. I don't know how to handle this case properly, but in the meantime you can use a full qualified annotation:

```
# @meta author:value: [John Doe](https://blog.example.com)
```

**Comment by atcommander** [comment]
I having what I think is a similar issue where on a multi line annotation it doesn't properly render indentation.  Would it be possible to implement an escape character that would allow you to denote that it isn't being used as a delimiter?

**Comment by xoxys** [comment]
Can you give an example please? This issue sounds a bit different.

**Comment by atcommander** [comment]
When create annotation like...

```yaml
# @meta author: >
# Wazuh
#
# ### Based on previous work from dj-wasabi
#
#   https://github.com/dj-wasabi/ansible-ossec-server
# @end
```
It  produces the following...

```markdown
## Author

Wazuh

### Based on previous work from dj-wasabi

https://github.com/dj-wasabi/ansible-ossec-server
```
with the link not being indented by two spaces even though I put them there

**Comment by xoxys** [comment]
That's an unrelated issue, and we currently don't support indentations.
