### ISSUE TITLE
recursive execution based on .ansibledoctor.yml

### ISSUE THREAD

**Issue by Rendanic** [thegeeklab/ansible-doctor#439]
I did some tests with this project and I will use it for [#oravirt/ansible-oracle](https://github.com/oravirt/ansible-oracle).
It looks really great for me.

There is 1 big wish:

- recursive search for .ansibledoctor.yml
What about an option to search in roles for '.ansibledoctor.yml' and execute ansible-doctor in each directory with this file?
That will allow 1 execution for all roles.
Finally this makes a CI Action very simpel at the end. I like to test for missing executions of ansible-doctor for new commits in a PR.
- support for pre-commit
If the previous functionality is existing, it is very simpel to add pre-commit for git.

Regards
Thorsten

**Comment by xoxys** [comment]
Thanks for your feedback. 

> recursive search for .ansibledoctor.yml

I am not really happy with this idea. Why make a decision based on an existing `.ansibledoctor.yml` file? What if someone just wants to use the default settings and doesn't have an `.ansibledoctor.yml` or uses another file with `--config`? I have no problem implementing a `--recursive` where we run ansible-doctor from any **direct** subdirectory of the given base dir, but if you need custom looping logic, that can be accomplished easily (and flexible) with a shell loop.

> support for pre-commit

Will look into this again, as multiple people have requested it now :+1:

**Comment by Rendanic** [comment]
What about a switch for:
- expect a directory where roles are placed
- go into each role and execute `ansible-doctor`

Such an option is really missing for easy usage in CI/CD and/or pre-commit.

**Comment by Rendanic** [comment]
Could you implement the `--recursive` option?
That could help a lot in adding support for pre-commit.
