### ISSUE TITLE
How to create tables?

### ISSUE THREAD

**Issue by Rendanic** [thegeeklab/ansible-doctor#444]
I want to create a table:

```
# @var test: >
#
# | Attribute | Description |
# | --- | --- |
# | att | test |
#
# @end
```

expected result:

```
### test

| Attribute | Description |
| --- | --- |
| att | test |
```

result:
```
### test

| Attribute | Description | | --- | --- | | att | test |
```

An extra linefeed is not allowed in markdown:
```
### test

| Attribute | Description |

| --- | --- |

| att | test |
```
The last example could easily created but is not working due to wrong syntax.

Is there a way to create tables with annotations?

Kind Regards
Thorsten

**Comment by xoxys** [comment]
Thanks for the report!
