### ISSUE TITLE
Description uses a new line for each word character

### ISSUE THREAD

**Issue by ntimo** [thegeeklab/ansible-doctor#456]
## Description
When using ansible-doctor 2.0 for a ansible role with the following in the `meta/main.yml` this is written in to the readme. As you can see ansible doctor uses a new line for each letter which is kind of strange. 

`meta/main.yml`:
```
  description: Installs Sentry.io on premise self hosted version.
```

`README.md´:
```
# common_roles_pre

I
n
c
l
u
d
e
s

c
o
m
m
o
n

p
r
e

A
n
s
i
b
l
e

r
o
l
e
s

t
h
a
t

a
r
e

r
u
n

b
e
f
o
r
e

t
h
e

m
a
i
n

r
o
l
e
.

## Table of content

```

**Comment by ntimo** [comment]
This appears to be related to: https://github.com/thegeeklab/ansible-doctor/pull/446

**Comment by xoxys** [comment]
Thanks for the report!
