### ISSUE TITLE
conflict between ansible-doctor and ansible-lint

### ISSUE THREAD

**Issue by Rendanic** [thegeeklab/ansible-doctor#495]
I get the following error, during installation of `ansible-lint` and `ansible-doctor` in same python environment:

```
The conflict is caused by:
    ansible-doctor 2.0.3 depends on ruamel.yaml==0.17.21
    ansible-lint 6.16.0 depends on ruamel.yaml<0.18 and >=0.17.24
```

Does ansible-doctor really need this hard dependency?

**Comment by xoxys** [comment]
Yes, please use a dedicated virtual env to install ansible-doctor (which is recommended for every python tool anyway).
