### ISSUE TITLE
Var options "type" and "deprecated" aren't available in standard template

### ISSUE THREAD

**Issue by wlitke** [thegeeklab/ansible-doctor#506]
In ansible-doctor version 2.0.3 the feature "extend var options with type and deprecated (https://github.com/thegeeklab/ansible-doctor/pull/462)" has been introduced. Unfortunately the default "readme" template hasn't been extended as well.
In order to use the new options it seems to be necessary to create an own template which is a kind of unfortunate.

**Comment by xoxys** [comment]
That's correct. Those options are text options without any convention, e.g. 

```yaml
# @var docker_registry_password:deprecated: true
# @var docker_registry_password:deprecated: since v1.0.0
```

We would need to find a way to include this in the standard templates. How should these options be interpreted and the information visualized? Should they simply be added as text? I am open to ideas. @germainlefebvre4 how do you present these options?

---

### demo_role_dict

> **Deprecated:** true
> **Type:** string

If a variable need some more explanation, this is a good place to do so.

#### Default value

```YAML
demo_role_dict:
  key1:
    sub: some value
```

**Comment by wlitke** [comment]
Thanks for your very quick reply. What do you think about the below view?
Regarding the deprecated option: I guess deprecated variables aren't used that often therefore I would avoid to put the wording "deprecated" to every variable (even when the boolean value makes clear whether a variable is deprecated or not).

---

### demo_role_dict (deprecated)

If a variable need some more explanation, this is a good place to do so.

**Type**: string

**Default value**
```yaml
demo_role_dict:
  key1:
    sub: some value
```

**Comment by xoxys** [comment]
But what if someone sets `# @var docker_registry_password:deprecated: since v1.0.0`? We just ignore the text and just flag variables as deprecated regardless of the given value?

**Comment by xoxys** [comment]
The idea was to just add `Deprecated: <text-goes-here>` if `deprecated` annotation is present. If `deprecated` is not set for a variable I agree, it should not appear on the template output as well.

**Comment by xoxys** [comment]
You are absolutely right, that would not look nice :) Ok let's do it that way for now.
