### ISSUE TITLE
Can not open template dir

### ISSUE THREAD

**Issue by trotro** [thegeeklab/ansible-doctor#518]
Hi,

I think there is a bug when using a custom template file. We have the error 
`[CRITICAL] Can not open template dir ${HOME}/ansible-doctor/README.md.j2`

Config is passed through env
```bash
export ANSIBLE_DOCTOR_TEMPLATE_DIR=${HOME}/ansible-doctor
export ANSIBLE_DOCTOR_TEMPLATE=README.md.j2
```

In the Generator._scan_template function there is a [test for the custom template directory](https://github.com/thegeeklab/ansible-doctor/blob/4888d01fae49ca8df8ce15a9730e38b9b1f122e4/ansibledoctor/doc_generator.py#L39C9-L39C50). But this test is using the full path of the template file. So it fails everytime.

The [config.get_template function](https://github.com/thegeeklab/ansible-doctor/blob/584e212f52fc3f08d0c76add127813ff4c85f0e2/ansibledoctor/doc_generator.py#L39) used to set the `template_dir` var in the doc_generator.py file is returning the full path.

You may consider using `os.path.dirname(template_dir)` on [L40 to L43](https://github.com/thegeeklab/ansible-doctor/blob/584e212f52fc3f08d0c76add127813ff4c85f0e2/ansibledoctor/doc_generator.py#L40) instead of `template_dir`.

I'm using version 2.1.1.

Thank you for your work

edit: add ansible-doctor version

**Comment by xoxys** [comment]
Hi,

> ```shell
> export ANSIBLE_DOCTOR_TEMPLATE_DIR=${HOME}/ansible-doctor
> export ANSIBLE_DOCTOR_TEMPLATE=README.md.j2
> ```

That's just not how templates are working. As the error message `Can not open template dir ${HOME}/ansible-doctor/README.md.j2`  is looking for a template _dir_ not while a file `README.md.j2` is given.

Taking a look at the built-in templates https://github.com/thegeeklab/ansible-doctor/tree/main/ansibledoctor/templates might explain the structure a bit better. The correct settings for the env vars would be:

```
export ANSIBLE_DOCTOR_TEMPLATE_DIR=${HOME}/ansible-doctor/templates
export ANSIBLE_DOCTOR_TEMPLATE=readme
```

The `ANSIBLE_DOCTOR_TEMPLATE_DIR` is the base directory where all available templates resist. For each template, a subdirectory within the base directory is required. `ANSIBLE_DOCTOR_TEMPLATE` is the name of the template subdirectory, _not_ a filename.

**Comment by trotro** [comment]
> The `ANSIBLE_DOCTOR_TEMPLATE_DIR` is the base directory where all available templates resist. For each template, a subdirectory within the base directory is required. `ANSIBLE_DOCTOR_TEMPLATE` is the name of the template subdirectory, _not_ a filename.

Oh right ! I misunderstood that part. Thank you for the explanation.

**Comment by xoxys** [comment]
No problem, glad to help.
